sudo: required
dist: trusty
language: node_js

node_js:
  - 6

services:
  - postgresql

before_script:
  - psql "CREATE docman SUPERUSER with password 'docman'"
  - psql -c 'create database database_test;' -U postgres
script:
  - npm test

after_script:
  - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
